### ISSUE TITLE
DNS issue(s) with new hassio_supervisor version (image 208 and above) - [supervisor.dbus.nmi_dns] No DnsManager support on the host. Local DNS functions have been disabled.

### ISSUE THREAD

**Issue by Johaik** [postlund/hassio-compose#3]
Hey, i'm using this docker-compose for the past few months (thanks!) and all of a sudden things become more problematic.
i'm using:
```
NAME="Ubuntu
VERSION="18.04.4 LTS (Bionic Beaver)
```
regular computer to run this docker-compose and i noticed that the DNS container is not longer work with the warning below and after this i'm getting:

```
hassio_supervisor | 20-03-09 19:58:52 ERROR (SyncWorker_11) [supervisor.docker] Can't create container from addon_core_duckdns: 404 Client Error: Not Found ("No such image: homeassistant/amd64-addon-duckdns:1.10")
hassio_supervisor | 20-03-09 19:58:52 ERROR (SyncWorker_17) [supervisor.docker] Can't create container from addon_a0d7b954_portainer: 404 Client Error: Not Found ("No such image: hassioaddons/portainer-amd64:1.0.0")
hassio_supervisor | 20-03-09 19:58:52 ERROR (MainThread) [asyncio] Task exception was never retrieved
hassio_supervisor | future: <Task finished coro=<Addon.start() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:472> exception=AddonsError()>
hassio_supervisor | Traceback (most recent call last):
hassio_supervisor |   File "/usr/src/supervisor/supervisor/addons/addon.py", line 493, in start
hassio_supervisor |     raise AddonsError() from None
hassio_supervisor | supervisor.exceptions.AddonsError
hassio_supervisor | 20-03-09 19:58:52 ERROR (MainThread) [asyncio] Task exception was never retrieved
hassio_supervisor | future: <Task finished coro=<Addon.start() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:472> exception=AddonsError()>
hassio_supervisor | Traceback (most recent call last):
hassio_supervisor |   File "/usr/src/supervisor/supervisor/addons/addon.py", line 493, in start
hassio_supervisor |     raise AddonsError() from None
hassio_supervisor | supervisor.exceptions.AddonsError
hassio_supervisor | 20-03-09 19:58:57 INFO (SyncWorker_12) [supervisor.docker.interface] Start homeassistant/qemux86-64-homeassistant
hassio_supervisor | 20-03-09 19:59:02 ERROR (MainThread) [supervisor.homeassistant] Home Assistant has crashed!
hassio_supervisor | 20-03-09 19:59:02 INFO (MainThread) [supervisor.addons] Phase 'application' start 2 add-ons
hassio_supervisor | 20-03-09 19:59:02 ERROR (SyncWorker_16) [supervisor.docker] Can't create container from addon_core_configurator: 404 Client Error: Not Found ("No such image: homeassistant/amd64-addon-configurator:4.7")
hassio_supervisor | 20-03-09 19:59:03 ERROR (SyncWorker_0) [supervisor.docker] Can't create container from addon_a0d7b954_nodered: 404 Client Error: Not Found ("No such image: hassioaddons/node-red-amd64:6.1.3")
hassio_supervisor | 20-03-09 19:59:03 ERROR (MainThread) [asyncio] Task exception was never retrieved
hassio_supervisor | future: <Task finished coro=<Addon.start() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:472> exception=AddonsError()>
hassio_supervisor | Traceback (most recent call last):
hassio_supervisor |   File "/usr/src/supervisor/supervisor/addons/addon.py", line 493, in start
hassio_supervisor |     raise AddonsError() from None
hassio_supervisor | supervisor.exceptions.AddonsError
hassio_supervisor | 20-03-09 19:59:03 ERROR (MainThread) [asyncio] Task exception was never retrieved
hassio_supervisor | future: <Task finished coro=<Addon.start() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:472> exception=AddonsError()>
hassio_supervisor | Traceback (most recent call last):
hassio_supervisor |   File "/usr/src/supervisor/supervisor/addons/addon.py", line 493, in start
hassio_supervisor |     raise AddonsError() from None
hassio_supervisor | supervisor.exceptions.AddonsError
```

I've tried to use older version but it's keep update the image 
also i've tried to set the DNS address manually and also i was able to reproduce this issue on other machines.

**Comment by postlund** [comment]
Sorry, I have no idea what happens here 😟 I don't have this problem myself. Have you tried searching the forums, in case someone else has similar issues?
